<a href="https://colab.research.google.com/github/aliawofford9317/LSAMP_Python_Course2024/blob/DanielaaVargas/Lesson_4b_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercises for participation credit
1. Combine the `student_data1` and `student_data2` into a single dataframe using the `concat()` method. The dataframes must be joined through the rows axis. Both dataframes are provided below.
2. Combine the `student_data3` and `student_data4` into a single dataframe using the common name column. The dataframes must be joined by the name column. You can use `merge()` method.
3. Merge `data1` and `data2` using the keys from the left dataframe only. You will need to use a `left` merge for this.

In [52]:
%%capture

def fetch_data():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("LSAMP_Python_Course2024"):
    shutil.rmtree("LSAMP_Python_Course2024")
  !git clone https://github.com/aliawofford9317/LSAMP_Python_Course2024.git
  for file in os.listdir("LSAMP_Python_Course2024"):
    if file.endswith((".txt",".csv")):
      shutil.copy("LSAMP_Python_Course2024/{}".format(file),cwd)
fetch_data()

In [53]:
import pandas as pd
import numpy as np

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [54]:
# Exercise 1 data
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

In [62]:
Conc = pd.concat([student_data1,student_data2])
Conc

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [63]:
# Exercise 2 data
student_data3 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks_test1': [200, 210, 190, 222, 199]})

student_data4 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
        'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks_test2': [201, 200, 198, 219, 201]})

In [64]:
NaC = pd.merge(student_data3,student_data4,on='student_id')
NaC

  student_id            name_x  marks_test1            name_y  marks_test2
0         S1  Danniella Fenton          200  Danniella Fenton          201
1         S2      Ryder Storey          210      Ryder Storey          200
2         S3      Bryce Jensen          190      Bryce Jensen          198
3         S4         Ed Bernal          222         Ed Bernal          219
4         S5       Kwame Morin          199       Kwame Morin          201

In [77]:
# Exercise 3 data
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})
display('data1','data2')

data1
  key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3

data2
  key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3

In [78]:
display("pd.merge(data1,data2,how='left')")

pd.merge(data1,data2,how='left')
  key1 key2   P   Q    R    S
0   K0   K0  P0  Q0   R0   S0
1   K0   K1  P1  Q1  NaN  NaN
2   K1   K0  P2  Q2   R1   S1
3   K1   K0  P2  Q2   R2   S2
4   K2   K1  P3  Q3  NaN  NaN