<a href="https://colab.research.google.com/github/aliawofford9317/LSAMP_Python_Course2024/blob/DanielaaVargas/Lesson_4a_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Practice Exercise**
1. Using the olympics dataset, check if the Country column is unique. If it is unique set the column as the new index.
2. Check that the dataset does not contain null values.
3. Sort the countries by Combined total medals in descending order. Use inplace=True. You can use the sort_values() method.
4. Apply the medal_count function to the dataframe with map() over the Combined total column. The function is given in the following code block.

In [1]:
import pandas as pd
import numpy as np

In [2]:
def fetch_data():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("LSAMP_Python_Course2024"):
    shutil.rmtree("LSAMP_Python_Course2024")
  !git clone https://github.com/aliawofford9317/LSAMP_Python_Course2024.git
  for file in os.listdir("LSAMP_Python_Course2024"):
    if file.endswith((".txt",".csv")):
      shutil.copy("LSAMP_Python_Course2024/{}".format(file),cwd)
fetch_data()

Cloning into 'LSAMP_Python_Course2024'...
remote: Enumerating objects: 231, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 231 (delta 90), reused 123 (delta 65), pack-reused 70
Receiving objects: 100% (231/231), 2.57 MiB | 10.37 MiB/s, done.
Resolving deltas: 100% (126/126), done.

In [9]:
df = pd.read_csv('olympics.csv', header=1)
df.head()

,Unnamed: 0,? Summer,01 !,02 !,03 !,Total,? Winter,01 !.1,02 !.1,03 !.1,Total.1,? Games,01 !.2,02 !.2,03 !.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [14]:
Names =  {'Unnamed: 0': 'Country',
               '? Summer': 'Summer Olympics',
               '01 !': 'Gold',
               '02 !': 'Silver',
               '03 !': 'Bronze',
               '? Winter': 'Winter Olympics',
               '01 !.1': 'Gold.1',
               '02 !.1': 'Silver.1',
               '03 !.1': 'Bronze.1',
               '? Games': '# Games',
               '01 !.2': 'Gold.2',
               '02 !.2': 'Silver.2',
               '03 !.2': 'Bronze.2'}

df.rename(columns = Names, inplace=True)
df.head()

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
0,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
1,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
2,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
3,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
4,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [17]:
df['Country'].is_unique

True

In [19]:
df.isnull().sum()

Country            0
Summer Olympics    0
Gold               0
Silver             0
Bronze             0
Total              0
Winter Olympics    0
Gold.1             0
Silver.1           0
Bronze.1           0
Total.1            0
# Games            0
Gold.2             0
Silver.2           0
Bronze.2           0
Combined total     0
dtype: int64

In [21]:
df.sort_values(by='Combined total', ascending=False, inplace=True)
df.head()

,Country,Summer Olympics,Gold,Silver,Bronze,Total,Winter Olympics,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
146,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579
135,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
106,Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
49,Great Britain (GBR) [GBR] [Z],27,236,272,272,780,22,10,4,12,26,49,246,276,284,806
44,Germany (GER) [GER] [Z],15,174,182,217,573,11,78,78,53,209,26,252,260,270,782

In [22]:
def medal_count(item):
    if item >= 100:
        return 'Lots of medals'
    if item < 100:
        return 'Few medals'

In [27]:
Medals =  df['Combined total'].map(medal_count)
Medals

146    Lots of medals
135    Lots of medals
106    Lots of medals
49     Lots of medals
44     Lots of medals
            ...
52         Few medals
53         Few medals
140        Few medals
61         Few medals
127        Few medals
Name: Combined total, Length: 147, dtype: object